---
- hosts: dnode
  tasks: 
  - name: disable firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
  - name: copy hostfile
    copy:
      src: /etc/hosts
      dest: /etc/hosts
