---
- hosts: dnode
  tasks: 
  - name: disable firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
  - name: copy hostfile
    copy:
      src: /etc/hosts
      dest: /etc/hosts
  - name: disable swap
    command: swapoff --all
  - name: comment swap
    lineinfile: 
      path: /etc/fstab
      regexp: '^(\/\S+\s+swap\s+.*)$'
      line: '# \1'
      backrefs: yes
